---

- name: Configure pooptube
  hosts: localhost
  vars_files:
    - secrets.yml
  tasks:
          - name: Configure keyboard
            copy: src=keyboard dest=/etc/default/keyboard mode=0755 owner=root group=root
            
          - name: Update apt
            apt: update_cache=yes

          - name: Upgrade existing packages
            apt: upgrade=dist

          - name: Install packages
            apt: name={{ item }} state=present
            with_items:
              - pianobar
              - mlocate

          - name: Install pip packages
            shell: pip3 install pyyaml

          - name: Create pianobar config dir
            file: path=/root/.config/pianobar state=directory mode=0755 owner=root group=root

          - name: Render pianobar config
            template: src=config.j2 dest=/root/.config/pianobar/config mode=0755 owner=root group=root

          - name: Fix ALSA config file
            shell: sed -i 's/pcm.front cards.pcm.front/pcm.front cards.pcm.default/g' /usr/share/alsa/alsa.conf

          - name: Force 3.5mm jack audio output
            shell: amixer cset numid=3 1

          - name: Set Volume to 100%
            shell: amixer -c 0 set PCM playback 100% unmute

          - name: Create dir for pianobar scripts
            file: path=/root/pianobar_scripts state=directory mode=0755

          - name: Install pianobar config
            copy: src={{ item }} dest=/root/.config/pianobar/{{ item }} mode=0755
            with_items:
              - eventcmd.py
              - schedule.yml

          - name: Install pianobar scripts
            copy: src={{ item }} dest=/root/pianobar_scripts/{{ item }} mode=0755
            with_items:
              - pianobar_wrapper.py
              - crashrestart_audio.sh

          - name: Install gcloud SDK
            shell: 'export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"; echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list; curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -; sudo apt-get update && sudo apt-get install -y google-cloud-sdk'

          - name: Create dir for gcloud scripts
            file: path=/root/gcloud_scripts state=directory mode=0755

          - name: Render gcloud scripts (from templates)
            template: src={{ item }}.j2 dest=/root/gcloud_scripts/{{ item }} mode=0755
            with_items:
             - gcloud_sync_dns.sh
             - gcloud-dns-bot.json

          - name: Render gcloud DNS cron job
            cron: name="update gcloud dns" minute="*/1" job="/root/gcloud_scripts/gcloud_sync_dns.sh >> /var/log/gcloud_sync_dns.log 2>&1"

          - name: Render creashrestart audio cron job
            cron: name="update gcloud dns" minute="*/1" job="/root/pianobar_scripts/crashrestart_audio.sh >> /var/log/crashrestart_audio.sh 2>&1"

