---

- name: Configure pooptube
  hosts: localhost
  vars:
          pandora_email: pooptube@gmail.com
          pandora_pass: poop
  tasks:
          - name: Configure keyboard
            copy: src=keyboard dest=/etc/default/keyboard mode=0755 owner=root group=root
            
          - name: Update apt
            apt: update_cache=yes

          - name: Upgrade existing packages
            apt: upgrade=dist

          - name: Install packages
            apt: name={{ item }} state=present
            with_items:
              - pianobar
              - mlocate

          - name: Create pianobar config dir
            file: path=/root/.config/pianobar state=directory mode=0755 owner=root group=root

          - name: Render pianobar config
            template: src=config.j2 dest=/root/.config/pianobar/config mode=0755 owner=root group=root

          - name: Fix ALSA config file
            shell: sed -i 's/pcm.front cards.pcm.front/pcm.front cards.pcm.default/g' /usr/share/alsa/alsa.conf

          - name: Force 3.5mm jack audio output
            shell: amixer cset numid=3 1

          - name: Create dir for pianobar scripts
            file: path=/root/pianobar_scripts state=directory mode=0755

          - name: Install pianobar config
            copy: src={{ item }} dest=/root/.config/pianobar/{{ item }} mode=0755
            with_items:
              - eventcmd.py
              - schedule.yml

          - name: Install pianobar scripts
            copy: src={{ item }} dest=/root/pianobar_scripts/{{ item }} mode=0755
            with_items:
              - pianobar_wrapper.py

